language: node_js
node_js:
  - "5"

install:
  - npm install
  - npm install --save-dev coveralls

script:
  - npm test
  - ./node_modules/.bin/eslint -c .eslintrc --ext .js src

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
